apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    exporters:
      debug:
        verbosity: detailed

      otlphttp/traces:
        endpoint: http://tempo-tempo:4318
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [debug, otlphttp/traces]
