apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dev
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token
    receivers:
      otlp/grpc:
        protocols:
          grpc: {}
      otlp/http:
        protocols:
          http: {}

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: tempo-tempo-gateway.hermes.svc.cluster.local:4317
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: dev  # tenantName

      otlphttp:
        endpoint: https://tempo-tempo-gateway.hermes.svc.cluster.local:8080/api/traces/v1/dev
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: dev

    service:
      extensions: [bearertokenauth]
      pipelines:
        metrics:
          receivers: [otlp/http]
          processors: [memory_limiter,batch]
          exporters: [debug]
        traces/grpc:
          receivers: [otlp/grpc]
          processors: [memory_limiter,batch]
          exporters: [debug, otlp]
        traces/http:
          receivers: [otlp/http]
          processors: [memory_limiter,batch]
          exporters: [debug, otlphttp]
