
# Example: https://github.com/grafana/tempo-operator/blob/main/tests/e2e-openshift/monolithic-multitenancy-openshift/01-install-tempo.yaml
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: tempo
spec:
  ingestion:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  resources:
    limits:
      cpu: '2'
      memory: 5Gi
  multitenancy:
    enabled: true
    mode: openshift
    authentication:
    - tenantName: dev
      tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
    - tenantName: prod
      tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
  jaegerui:
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
    route:
      enabled: true
    enabled: true
  storage:
    traces:
      backend: memory